.TH GROUP.CONF 5 "September 27, 2008" "creuvux-0.70" "Creuvux Manual" 
.SH NAME
group.conf - Configuration file for creuvux's groups
.SH DESCRIPTION
group.conf contains a list of creuvux clients/groups. 
.SS Options:

	username:groupname_1,groupname_2
.TP
.B Exemple:
.I user1:grp1,grp2

.I user2:grp1,grp3

.I user3:grp4

.SH SEE ALSO
creuvuxd(1), group.conf(5) 
