.TH "Command_options" 3 "Lundi Février 25 2013" "Creuvuxd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Command_options \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "off_t \fBbegin\fP"
.br
.ti -1c
.RI "off_t \fBend\fP"
.br
.ti -1c
.RI "char * \fBgrp\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "char * \fBaddr\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBmail\fP"
.br
.ti -1c
.RI "char * \fBsha1\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBlst_file\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBold_sha1\fP"
.br
.ti -1c
.RI "char * \fBgenre\fP"
.br
.ti -1c
.RI "char * \fBcomment\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Creuvuxd à partir du code source\&.
