.TH "ServerOptions" 3 "Lundi Février 25 2013" "Creuvuxd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerOptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBnum_ports\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "int \fBbandwidth\fP"
.br
.ti -1c
.RI "char * \fBchroot_directory\fP"
.br
.ti -1c
.RI "char * \fBconfig\fP"
.br
.ti -1c
.RI "char * \fBlisten_addrs\fP"
.br
.ti -1c
.RI "int \fBaddress_family\fP"
.br
.ti -1c
.RI "char * \fBhost\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.ti -1c
.RI "char * \fBpid\fP"
.br
.ti -1c
.RI "int \fBsec\fP"
.br
.ti -1c
.RI "char * \fBpassphrase\fP"
.br
.ti -1c
.RI "char * \fBupload_directory\fP"
.br
.ti -1c
.RI "char * \fBpublic_directory\fP"
.br
.ti -1c
.RI "char * \fBstat_repport\fP"
.br
.ti -1c
.RI "off_t \fBdb_max\fP"
.br
.ti -1c
.RI "off_t \fBdb_min\fP"
.br
.ti -1c
.RI "char * \fBipdb\fP"
.br
.ti -1c
.RI "int * \fBportdb\fP"
.br
.ti -1c
.RI "char * \fBdbname\fP"
.br
.ti -1c
.RI "char * \fBdbuser\fP"
.br
.ti -1c
.RI "char * \fBdbpassw\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Creuvuxd à partir du code source\&.
