.TH "slist_t" 3 "Lundi Février 25 2013" "Creuvuxd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slist_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBis_dir\fP"
.br
.ti -1c
.RI "struct slist * \fBnext\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Creuvuxd à partir du code source\&.
