.TH "Ustat" 3 "Lundi Février 25 2013" "Creuvuxd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ustat \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBnb_sync\fP"
.br
.ti -1c
.RI "int \fBnb_put\fP"
.br
.ti -1c
.RI "int \fBnb_get\fP"
.br
.ti -1c
.RI "int \fBnb_comment\fP"
.br
.ti -1c
.RI "int \fBnb_tot\fP"
.br
.ti -1c
.RI "off_t \fBsize_get\fP"
.br
.ti -1c
.RI "off_t \fBsize_put\fP"
.br
.ti -1c
.RI "off_t \fBsize_tot\fP"
.br
.ti -1c
.RI "off_t \fBsize_comment\fP"
.br
.ti -1c
.RI "off_t \fBdelta_sync\fP"
.br
.ti -1c
.RI "off_t \fBdelta_get\fP"
.br
.ti -1c
.RI "off_t \fBdelta_put\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char * \fBpseudo\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Creuvuxd à partir du code source\&.
